### ISSUE TITLE
SohoLookUpComponent return false onBeforeShow

### ISSUE THREAD

**Issue by berjoh0** [infor-design/enterprise-ng#1006]
When executing response(false); in BeforeShow it's not possible to click search/lookup icon again, nothing will happen.

**Comment by tmcconechy** [comment]
There is a beforeShow callback in settings if you return false it should not show the dialog

https://github.com/infor-design/enterprise/blob/master/src/components/lookup/lookup.js#L345

Here is one example https://master-enterprise.demo.design.infor.com/components/lookup/test-beforeshow-cancel.html

DOes that help? If not perhaps you can modify this example to show me the issue of it not working

**Comment by berjoh0** [comment]
when executing response(false) then dialog will not show but when I press the lookup icon to issue the lookup again nothing happens. I've tried using arrow function and normal function. The function looks like.

<-- HTML -->
<input soho-lookup type="text" id="itemSearch" name="itemSearch"
[(ngModel)]="lookupItemSearch"
[beforeShow]="onItemSearchBeforeShow"
(change)="onItemSearchChange($event)"
title="Lookup Item search"
field="value"/>


<-- TYPESCRIPT -->

	onItemSearchBeforeShow =  (api: SohoLookupComponent, response: any) => {
		Log.debug("ItemBeforeShow");
		response(false);
	}

OR 

	onItemSearchBeforeShow(api: SohoLookupComponent, response: any) {
		Log.debug("ItemBeforeShow");
		response(false);
	}

**Comment by tmcconechy** [comment]
Ok, I guess im a bit confused about this issue. Also in future please try to use the issue template in the description as it gets more info on the bug. https://github.com/infor-design/enterprise-ng/issues/new/choose

Isnt this working the same way on https://master-enterprise.demo.design.infor.com/components/lookup/test-beforeshow-cancel.html i.e. if you return false always from beforeShow its never going to open the dialog. Thats pretty much the idea. I think you would want to sometimes return true and let it open. Or maybe you want to disable the whole field?

I also tried to test this example https://github.com/infor-design/enterprise-ng/blob/master/src/app/lookup/lookup.demo.ts#L244 and it seems working as i expect

See http://localhost:4200/ids-enterprise-ng-demo/lookup and click example "Products (Cancel Before Open" and i see it firing like i expect.

Perhaps i'm missing info that would be in the issue template like an example and expected behavior and version?

Also you could use https://stackblitz.com/edit/ids-quick-start-910 to make an example thats runable to show the issue.

**Comment by berjoh0** [comment]
The response function() and response(false) works as excepted regarding about opening and not opening the dialog but when I try to click the lookup icon again when response(false) nothing happens, the beforeshow doesn't fire again, I use the beforeshow to validate that the search will show something and if nothing is found I show a message instead. I'll continue investigating, is there an example how the "Click" should work? How to fire the dialog from inside the SohoLookupClickFunction.

**Comment by tmcconechy** [comment]
No we currently don't have an example showing beforeOpen with the click. Put its possible there is an issue there. 
Can you make a reproduction of this issue.

Idea around the click is - you want click to do something special. So if your using that it just fires a click event and then your on your own to do whatever actions you want. It will no longer open the dialog normally.
