### ISSUE TITLE
Input: Add an API to select the text on focus

### ISSUE THREAD

**Issue by brianpettit** [infor-design/enterprise-ng#1010]
focus is already a method for the InputComponent.  Select is not.

**Comment by tmcconechy** [comment]
Seems like this was handled on https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1615933537261?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1615933537261&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1615933537261

In addition we have in fact add this to the 5.0 branch..

```
<ids-input type="text" label="Autoselect" value="Text select on focus" autoselect="true"></ids-input>
```

Please note there is an issue template https://github.com/infor-design/enterprise-ng/issues/new/choose that has details in it for making issues. This issue i do understand because i read the teams chat but if another developer picked this up they would maybe not know what to do here.

**Comment by dersgniw** [comment]
What is the 5.0 branch?

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise-wc -> its not ready yet for primetime tho. be a little while until it has full feature parity
