### ISSUE TITLE
Single Select Lookup - getting value as a string instead of object

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise-ng#1114]
**Describe the bug**
In 4.54.0 version we observed one issue with single select lookup. When we select any value, we get that object as string, In previous version it was showing all the information related to that object. 

We have reproduced this issue in strackblitz. Please refer below links.

https://stackblitz.com/edit/ids-quick-start-950-fc8huf - 4.51.1 version

https://stackblitz.com/edit/angular-ivy-rsfhng - 4.54.0 version

We have created two example with different SoHo version.  

**To Reproduce**
Steps for both projects:
1. Click on Lookup tab from menu
2. Open single select lookup and select any one record
3. Click on Apply button

You will see json result of ngModel attached to lookup(In this case it is selectedNodeList) and event.values parameter for (change) event of lookup.

For sosho version 4.51.1 it is all object like below:
{"id":566,"applicationInstanceGuid":"6d962a9d-82a9-40c4-9c7a-6e9ceefa4bcf","applicationInstanceName":"Application Instance 1","tenantId":null,"applicationLogicalID":null,"subscriptionID":null,"appTypeGuid":null,"applicationType":"app type 1","createdBy":null,"createdByID":null,"updatedBy":null,"creationDate":null,"updatedOn":null,"parentId":null,"clientIp":null,"sessionID":null,"processModules":null,"erpTypeId":null,"erpTypeName":null,"text":"Application Instance 1","isWriteBack":false,"isUserMap":false,"userMapFieldID":0,"_selected":true}

but for soho version 4.54.0 it is: "Application Instance 1"

**Expected behavior**
It should show all the information related to selected object.

**Version**
- ids-enterprise-ng: [v4.54.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@deep7102 could you take a look sooner than later this month?

**Comment by tmcconechy** [comment]
@dhumalkishor 

I took your fork and modified it so that the change event has the data from the data set in it please try this example https://stackblitz.com/edit/angular-ivy-adxfrh?file=src%2Fapp%2FLookup%2Fmock.data.ts

- open the lookup page
- open the lookup and select a value
- look in the console

With this example i realize the modal isn't being updated in the event data but perhaps you can just manually update that in the change event. So this is to get you started.

I'm actually not able to figure out why this even worked at all in 4.51 as to me it doesn't make any sense that it did since normally the change event just shows what is in the field setting since the Idea is you are selecting an ID not a value in most cases.

I didnt try to modify the solution on https://github.com/infor-design/enterprise-ng/blob/main/src/app/lookup/lookup-desc.demo.html we made for you but i think it could also work too by using https://github.com/infor-design/enterprise-ng/blob/main/src/app/lookup/lookup-desc.demo.ts#L120 in the change event.

Hope this can help you find a solution using this information. If not @deep7102 can help next week as he is out the rest of the week at least with personal issues or someone can look further.

**Comment by JangleShubham** [comment]
Hello @tmcconechy ,

Thanks for your suggestion, the change you suggested will not be affected for ngModel values bined, we can use same change event to change that value as well and we tried it.
But the problem is we have used single select lookup in across product, so this change need to done for all lookups on every page wherever it is been used.
Can you provide generic solution for this issue? 
It will be ok of you give patch in 4.54.0 itself.

Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment]
I’m not sure what the solution would look like because usually the model reflects what’s in the field but in this case you don’t want that.

let’s let @deep7102 take a look next week and see what he sees maybe he can come up with a better idea. 

To solve the issue maybe you can use my solution but wrap it in a component you make for your own use that solves it for the way your team? Then you can reuse your solution in the various places you need to?

**Comment by deep7102** [comment]
@dhumalkishor @JangleShubham 
By adding the attribute `[asobject]="true"` should give what we looking here so steps as:

https://stackblitz.com/edit/angular-ivy-rsfhng - 4.54.0 version
- go to: src > app > Lookup > lookup.demo.html
- add around line# 11 or 12 ` [asobject]="true"`

**Comment by jbrcna** [comment]
this is working as expected. moving ticket to Done. thanks
![image](https://user-images.githubusercontent.com/56722184/132824575-399d739b-eeec-4939-bac4-6d688ce9acb4.png)
