### ISSUE TITLE
Tooltip: Text is getting truncated when the content tooltip text is large

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise-ng#1141]
**Describe the bug**
This might be an edge case, when the tooltip text is long, the content tooltip is getting truncated.

**To Reproduce**
I have modified some files, please paste the files inside src/app/datagrid
[datagrid.zip](https://github.com/infor-design/enterprise-ng/files/7276823/datagrid.zip)

1. Go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-standalone-pager
2. Hover to any record on the product name column
3. You can see the text are getting truncated.

**Expected behavior**
Make a way to make a tooltip with large text fit, or either make it scrollable.

**Version**
- ids-enterprise-ng: 10.7.0

**Screenshots**

https://user-images.githubusercontent.com/29673378/135824576-9641b6b4-22a6-4c40-bac2-8b81a7a389b2.mp4

**Platform**
 - Device (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 94.0.4606.71 (Official Build) (64-bit)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-31079

**Comment by tmcconechy** [comment]
This is definitely an edge case. And seems like the wrong use of a tooltip. I'm not sure its something we would want to fix. We definitely cant have scrollable tooltips because they are not not clickable/actionable.

One other idea is to try and set the https://github.com/infor-design/enterprise/blob/main/src/components/tooltip/tooltip.js#L45 setting to something higher that could at last make it wider.

But the best solution would be to limit the amount of text you try to put in the tooltip. Or could maybe use a popup or modal  or an expandable row with the data.
