### ISSUE TITLE
Input: Clearable option not available

### ISSUE THREAD

**Issue by mgdfgodoy** [infor-design/enterprise-ng#1195]
**Describe the bug**
Missing clearable option for the input field.  I found the demo in enterprise, but it doesn't seem to be exposed in enterprise-ng.

**Expected behavior**
A clear button appears when typing inside an input field and clicking the button emits a clear event.

**Version**
- ids-enterprise-ng: v10.6.0

**Screenshots**
Missing clear button:
![image](https://user-images.githubusercontent.com/55127155/146173171-27de474e-8838-485d-af52-56330b5b9dc1.png)

How it should be:
![image](https://user-images.githubusercontent.com/55127155/146172548-db058cdb-b5f4-4890-9cf2-a09c12605150.png)
https://main-enterprise.demo.design.infor.com/components/input/example-clearable.html

**Comment by whernebrink** [comment]
@tmcconechy, is this something that could be implemented as a angular Directive instead of on the actual soho-input? We have had some issue using the soho-input in the past, and would be nice to simply apply a directive on a input in order for it to get the clearable functionality. I just tried the following:

```ts
import { Directive, ElementRef, AfterViewInit } from '@angular/core';

@Directive({
  selector: 'input[soho-clearable]',
})
export class SohoClearableDirective implements AfterViewInit {
  private jQueryElement?: JQuery;

  constructor(private element: ElementRef) {
    const inputElement = element.nativeElement as HTMLInputElement;
    this.jQueryElement = jQuery(inputElement)
  }

  ngAfterViewInit(): void {
    (this.jQueryElement as any).clearable();
  }
}
```

It "works" (appears when there is a value in the input, and clears the input when clicking the `x`), although does not look 100%, nor does it get the same markup/wrapper span as the seracfield:
![image](https://user-images.githubusercontent.com/73601152/146181593-ef422c32-33cf-4452-9a6e-ba6f30f43cb1.png)

Just an idea! :)

**Comment by tmcconechy** [comment]
It may be possible but considerable more work and time to do then adding the type. In addition in the 5.x Web components the option is still part of the component and sort of has to be that way there. So i think i'd lean to keeping it as an option based on it being that way in the future version and that we have plenty of work already.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
