### ISSUE TITLE
Tree Icons not updating correctly

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise-ng#128]
Steps to reproduce

1. Click sessionNode3

Expected: Folder icon should open (icon name: icon-started-folder-open)
Actual: Folder icon still closed (icon name: icon-started-folder-closed)

1. Click ruleNode9, icon initially is (icon-tree-node)
1. Click deactivate button from toolbar
1. ruleNode9 icon should be (icon-tree-doc)
1. Click sessionNode3, contents should collapse
1. Click sessionNode3 again, contents should expand
1. Observe ruleNode9 should be (icon-tree-doc)
1. Click deactivate for sessionNode3

Expected: sessionNode3 icon should be (open-folder) and ruleNode9 should stay (icon-tree-doc)
Actual: sessionNode3 icon becomes (closed-folder) and ruleNode9 reverts back to (icon-tree-node)

1. Refresh browser
1. Click sessionNode1, should collapsed and icon becomes (icon-started-folder-closed)
1. Click deactivate button for sessionNode1

Expected: Icon for sessionNode1 should be (closed-folder)
Actual: Icon for sessionNode1 becomes (open-folder)

Sample project:
[soho-tree-bug.zip](https://github.com/infor-design/enterprise-ng/files/2168922/soho-tree-bug.zip)

**Comment by tmcconechy** [comment]
Took a quick look at this. I was able to make it work in the attached project. The main issue is that you need to use the options folderIconOpen and folderIconClosed

You need to use those to correctly change the folders. You also cannot use different folder types. See attached project.

- upgraded project to 4.8.0 (since in 4.5.0 the folderIconOpen and folderIconClosed options are not present)
- removed getIcon code
- changed to use those options in ngOnIint

Then it all works. See updated example:

[Archive.zip](https://github.com/infor-design/enterprise-ng/files/2170875/Archive.zip)

**Comment by kenneth-acejo** [comment]
Having "icon-started-folder-open/icon-started-folder-closed" on top of "open-folder/closed-folder" is not supported then?

Alright, I guess our team will have to continue using our modified tree. Thanks Tim :)

**Comment by tmcconechy** [comment]
Yes thats right you can only change all the folders to new ones not mix and match.
