### ISSUE TITLE
Monthview - Monthview duplicates when Legend changes

### ISSUE THREAD

**Issue by LilBiggs** [infor-design/enterprise-ng#1305]
When the Legend Input binding is updated, the monthview is doubled on the screen and 2 monthviews are displayed.

**To Reproduce**
1. https://stackblitz.com/edit/ids-quick-start-1341-n7xfd2?file=src/app/app.component.html
2. Click on "Update Legend" button.

**Expected behavior**
When updating the legend, the legend will updated correctly and the monthview will not duplicate.

**Version**
- 13.4.1

**Screenshots**
![image](https://user-images.githubusercontent.com/6730716/170491625-1634348c-f1b9-4a8c-a9b3-ffdc789b9140.png)
![image](https://user-images.githubusercontent.com/6730716/170491646-1c76ee67-29de-44dd-ac04-f5a57a75c313.png)

**Platform**
- Any

**Additional context**
Team: Infor WFM

**Comment by anton-kurilov** [comment]
Hey @tmcconechy just curious about process here. Is there a label or anything to mark the severity of a bug? For example I would say this is a "blocker" to even have this component available in the library. Or would something like this just get prioritized to the top of the backlog without any additional labels needed? Thanks!

**Comment by tmcconechy** [comment]
I only look at this briefly before but it was prioritized to next sprint. I wasn't 100% sure if it was just the way you are doing it. I guess one might expect that changing the array binding the legend items would work but instead we provided a function you can call:

Example: https://main-enterprise.demo.design.infor.com/components/monthview/test-legend-loaded.html (changes when changing month)
Source: https://github.com/infor-design/enterprise/blob/main/app/views/components/monthview/test-legend-loaded.html#L39

Can you look at this example and see if it helps you get this legend items reloaded via the method?

BTW labels are critical/(none for normal)/minor/trivial or regression bug -> so i think the label is probably correct since its a "new thing" (unless its a regression?)

That all being said if this doesn't work its already prioritized to next sprint. I can try to put it in the current sprint if we get things done a little faster it might be possible but i think the method should work. Given the example i think it should help :)

**Comment by tmcconechy** [comment]
@ericangeles - WFM is requesting this one as its slightly blocking. We want to be able to set the array again in NG and have it update (possibly by calling loadLegend() in the EP code). Make sure the events on the days also do update when you set the array accordingly. I.E.

Note the following occurs
- monthviewrender fires
- in that we set legend with the array similar to https://main-enterprise.demo.design.infor.com/components/monthview/test-legend-loaded.html but not exactly
- both the legend and the day events for the legends should update (and not infinite loop)

**Comment by jbrcna** [comment]
this is working as expected. moving this ticket to Done. 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/56722184/173980955-9e297fff-b3b3-418d-b277-755e9fd3a22d.png">
