### ISSUE TITLE
SohoPopupmenu: Stops functioning after page reloaded

### ISSUE THREAD

**Issue by James-Carlin** [infor-design/enterprise-ng#1348]
<b>Describe the bug</b>

When creating a new quest on the Coleman platform, it was observed that after a user creates a new quest and the page is reloaded the soho popup menu stops functioning. There is no click event. 

<b>To Reproduce </b>
1. Navigate to Quests -> new quest
2. Drag and Drop any activity to the modeler
3. Type in the name for the quest
4. Validate that the option for Scoring is "Include only Label and Features columns for postprocessing"
5. Open console -> network
6. Save the quest
7. Change the option to "Incude all columns for postprocessing" -> SAVE button is not enabled -> should be!
8. Check the Network -> quest call -> preview:
Result: the option is not changed from "COMPAT" to "FULL"

<b>Expected Behaviour</b>
The popup menu should still function and allow user to change selection.

<b>Version</b>
13.1.1

<b>Screenshots</b>
![image](https://user-images.githubusercontent.com/56592791/180209259-5c6297fd-661a-4086-8625-3fb34b417b21.png)

<b>Platform</b>
OS Version: Windows 10

**Comment by tmcconechy** [comment]
Seems like this might be an issue for the "quests" application team? Not sure what that is. 

In order to fix issues with the components we need a reproduction.

Perhaps you can fork our stackblitz and make an example showing the issue https://stackblitz.com/edit/ids-quick-start-1411?file=src%2Fapp%2Fapp.component.ts as all this details seem app specific.

**Comment by tmcconechy** [comment]
Closing older issues with not enough info to reproduce.
