### ISSUE TITLE
Checkboxes not reading in attributes from HTML

### ISSUE THREAD

**Issue by pallisj** [infor-design/enterprise-ng#1491]
I have upgraded to the latest versions and checkboxes are not being set to disabled from the HTML. There are some pages that I can toggle this disabled attribute in the corresponding ts file if they are static fields but the dynamic checkboxes do not have the same ability. Your team had fixed this for dropdowns and date pickers in the previous version and it seems checkboxes have the same issue and my workaround isn't viable for our whole application.

1. create a dynamic popup modal with a check box
2. set the check box to disabled in the html

Expected: The checkbox will be disabled
Actual: The checkbox is editable

IDS v16.3.1
![6daa48e6-5547-4741-924a-3c69b818b508](https://github.com/infor-design/enterprise-ng/assets/129091848/ccc8808b-6bbf-4ec3-b67c-14f736040f1c)
![9c76dc2d-942a-4f3c-9dc6-926e0a27d688](https://github.com/infor-design/enterprise-ng/assets/129091848/81a6e42b-cf7d-42c5-99fd-32e7f4ab2e62)

This same issue was happening with date pickers and dropdown fields in IDS v15 and was fixed so this should be a similar solution.

**Comment by tmcconechy** [comment]
@ericangeles @yohannahbautista any way we can squeeze this in similar to previous fixes?

**Comment by ericangeles** [comment]
@yohannahbautista please check this one.

**Comment by yohannahbautista** [comment]
Hello, I'll still look into it, but would using [disabled] instead of [attr.disabled] work for this case in the mean time?
It's used similar in this example: http://localhost:4200/ids-enterprise-ng-demo/checkbox
<img width="965" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/85279127/6fa153b8-27b0-4b01-94b0-56c5c99f078d">

**Comment by yohannahbautista** [comment]
Hello, I made a stackblitz that shows an example I used to try and replicate the bug and I haven't been able to do it so far. Is this how it was implemented? If not, would it be possible to have an example, like in stackblitz or similar, as reference?
https://stackblitz.com/edit/ids-quick-start-1411-jpeuwm?file=src%2Fapp%2Fmodal.component.html

**Comment by pallisj** [comment]
Currently it is impossible for me to set a checkbox to disabled from any html. Checkboxes are never disabled in my application whether I use attr.disabled / attr.disable / disabled / disable / readonly / attr.readonly. I have to grab the form values by name in the ts and set them to disabled, but this doesn't work if I don't always have the name for the field if it is dynamically generated. All html disabling code is being ignored and should not be. Your example that you have from stackblitz that wouldn't work on my application. I don't know how we keep having inconsistencies with our results but I can try to get some sort of example for you. I was assuming it would be the same fix as the dropdown and datepicker fixes you had done before just in a different area that controls the checkboxes.

**Comment by tmcconechy** [comment]
@pallisj sorry should have checked this. i couldn't reproduce either. But i pushed an example that shows two ways of doing it now that work. Please checkout http://localhost:4200/ids-enterprise-ng-demo/checkbox

Example: https://github.com/infor-design/enterprise-ng/blob/main/src/app/checkbox/checkbox.demo.html#L7-L12

**Comment by pallisj** [comment]
@tmcconechy @yohannahbautista I made a very simplified page with just this code: 

> <div class="row">
	<div class="twelve columns">
		<div class="field">
			<h1 class="fieldset-title">{{ "SRM.ViewModel.FieldCaption.noReqConsRulesSelected" | translate }}</h1>
		</div>
		<div class="field">
			<input soho-checkbox type="checkbox" class="checkbox" formControlName="delAllDemands" name="delAllDemands" id="delAllDemands" [disabled]="true" />
			<label for="delAllDemands" class="checkbox-label">{{ 'SRM.ViewModel.FieldCaption.delAllDemands' | translate }}</label>
		</div>
	</div>
</div>

Result:
<img width="775" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/129091848/7748e6e2-30d9-44e6-8dd6-b1b6800d2972">


and the checkbox is not disabled. Does this not prove there is an issue from the upgrade? This worked as expected in our single and multitenant environments until this upgrade cycle when we went from IDS v10.1.0 to 16.3.1. It causes a lot of issues throughout AE if we cannot disable any of our checkbox fields.

**Comment by tmcconechy** [comment]
I'm not sure what this proves yet because the example works in our case so nothing "broke" there. But happy to help figure this out and it appears to do with reactive forms.

I first took your example and added it to the page. This indeed did not work but it gave an error: "formControlName must be used with a parent formGroup directive.  You'll want to add a formGroup directive and pass it an existing FormGroup instance (you can create one in your class)."

```
      <div class="field">
        <input soho-checkbox type="checkbox" class="checkbox" formControlName="delAllDemands" name="delAllDemands"
          id="delAllDemands" [disabled]="true" />
        <label for="delAllDemands" class="checkbox-label">Test</label>
      </div>
```

But this does work

```
      <div class="field">
        <input soho-checkbox type="checkbox" class="checkbox" name="delAllDemands"
          id="delAllDemands" [disabled]="true" />
        <label for="delAllDemands" class="checkbox-label">Test</label>
      </div>
```

Also see the issue if i go to src/app/form/form-reactive-form.demo.html and use this i see its not disabling...Seems to remove it in all cases

```
      <div class="field">
        <input soho-checkbox type="checkbox" id="checkbox" name="checkbox" formControlName="checkbox"
          (change)="onChange($event)" disabled>
        <label soho-label for="checkbox" [forCheckBox]="true">Checked</label>
      </div>
```

Do you have to do it a special way with reactive forms to do it like this:?https://stackoverflow.com/questions/42840136/disable-input-fields-in-reactive-form

I see in the DOM that reactive forms seems to remove the attribute and add `ng-reflect-is-disabled`
We could add this... maybe but not sure enough about reactive forms if there is a better way or there is something going on with it i dont yet follow.

```
[ng-reflect-is-disabled] + label {
    opacity: .2; // use actual disabled css
}
```

BTW we did not change much here around this except the angular version.

**Comment by tmcconechy** [comment]
@pallisj have a read here too https://stackoverflow.com/questions/40494968/reactive-forms-disabled-attribute seems to explain things people with similar issues had

**Comment by pallisj** [comment]
@tmcconechy Thank you very much for all of your suggestions. Removing the form control name solved my issues. I appreciate you and your whole team's help through this entire upgrade process!
