### ISSUE TITLE
Accordion scrollbar is disappeared

### ISSUE THREAD

**Issue by karakasatya** [infor-design/enterprise-ng#1559]
**Describe the bug**
Due to IDS latest release(addition of display: contents; to _nghost-ng-c******** class) the accordion scrollbar is not working. 

**To Reproduce**
1. Go to https://mingle-cqa-portal.cqa.inforcloudsuite.com/DDEELNINT_DEV and login then select sales manager home page then choose Customer Contacts widgets.
2. Click on kebob menu right side of the widget and then click on configure then choose company 190 then click on save then data will load and see the scroll is not showing.

**Expected behavior**
If we have more then 10 list items in the widget the scroll should appear & work.

**Version**
- ids-enterprise-ng: 4.85.0

**Screenshots**
<img width="950" alt="accordion-scroll-issue" src="https://github.com/infor-design/enterprise-ng/assets/145528086/495bd512-d034-4693-8aac-0ae98d13abc3">

<img width="946" alt="accordion-scroll-issue-2" src="https://github.com/infor-design/enterprise-ng/assets/145528086/d3004c52-c07f-4449-a412-660754119d8e">

When i add scrollable class to the soho-accordion element is also not working.

<img width="959" alt="accordion-scrollable-not-working-case" src="https://github.com/infor-design/enterprise-ng/assets/145528086/ee5d41a0-bca4-4eb8-aa55-10156ab25c54">

**If you can add scrollable class to the existing accordion class element this issue will be fixed.**

<img width="960" alt="accordion-scrollable-working-case" src="https://github.com/infor-design/enterprise-ng/assets/145528086/2a28d034-8303-4848-998d-f4feef23fce1">

**Platform**
 - Infor Application/Team Name: LN-Widgets
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: Chrome
 - Browser Version: 117.0.5938.92 (Official Build) (64-bit)

**Comment by volante007** [comment]
IDS needs steps to reproduce, in their samples or by creating a stackblitz, i.e. a reduced test case. 

I have created a stackblitz, which I think mimics how your widget is structured (in general, at least).

https://stackblitz.com/edit/ids-quick-start-1671-rm8su2?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

1. Expand a few accordion headers, see that no scroll appears
2. Change `app.component.css` so that `soho-accordion` uses `display: inline` (which it did prior to this change)
3. Expand a few accordion headers, scroll appears.

It's important to note that this display change seems to have a negative effect **for your specific structure of elements**, and might not be a problem in general or with a less complicated structure. Even though, if it is OK to only use `display: contents` in the module-nav context, it would be good to change this on the IDS side.

**Comment by tmcconechy** [comment]
ok @volante007 im on it

**Comment by volante007** [comment]
> ok @volante007 im on it

Hey Tim, sorry, it seems like it's already in the latest ids-enterprise-ng. I was confused by the fix version of 4.89.x mentioned here.

**Comment by tmcconechy** [comment]
Ok, @volante007 try it as im seeing this in 4.89 which would be 116.9 in the future.

**Comment by volante007** [comment]
Works fine on `ids-enterprise-ng@16.8.x` (latest) which uses `ids-enterprise@4.88.x` , so it's fixed in the latest available release :)
