### ISSUE TITLE
Search: Category search in compact mode is misaligned

### ISSUE THREAD

**Issue by mgdfgodoy** [infor-design/enterprise-ng#1605]
**Describe the bug**
When a category search field is set to compact mode, the dropdown appears smaller than the input field to the right. Search and dropdown icons are also misaligned with the category search text.

**To Reproduce**
1. Go to [this stackblitz](https://stackblitz.com/edit/category-search-compact?file=src%2Fapp%2Fcategory-search%2Fcategory-search.component.html).
2. Compare the two fields using "field" and "field-short".

**Expected behavior**
Dropdown and its icons are aligned with the input field height.

**Version**
- ids-enterprise-ng: v16.8.1

**Screenshots**
![image](https://github.com/infor-design/enterprise-ng/assets/55127155/51d18795-ca44-4ef3-b4b8-25b41fd09ef0)

![image](https://github.com/infor-design/enterprise-ng/assets/55127155/650dc964-bd72-48ad-884b-97b7ca89d3c0)

**Comment by whernebrink** [comment]
@tmcconechy, team: M3 :)

**Comment by whernebrink** [comment]
I'll added to the [Stackblitz](https://stackblitz.com/edit/category-search-compact-syhanb?file=src%2Fapp%2Fcategory-search%2Fcategory-search.component.html) a version where the `.form-layout-compact > .field` instead of just `.field-short` since this is also a case to cover:
![image](https://github.com/infor-design/enterprise-ng/assets/73601152/4ab69de9-7057-4e52-817e-d17be382cf16)
