### ISSUE TITLE
Charts: charts.setSelected() doesn't work if more than one chart is on the same page

### ISSUE THREAD

**Issue by DavidMoerman** [infor-design/enterprise-ng#1671]
**Describe the bug**
We use several instances of the SohoBarComponent and SohoChartComponent from ids-enterprise-ng on a single page. Calling the setSelected() function on the SohoBarComponent does not function reliably, as it will use the dataset of one of the others.
The underlying problem is in the sohoxi.js library. There are several "chars.setSelected()" functions defined, some have the third parameter "internals", but not all of them. In our case, the function defined on line 34535 (version 4.93.1) doesn't have this parameter and that causes the misbehaviour. When I fix that function by using the code of one of the other setSelected() implementations (like the one on line 30689), the functionality works as expected.

**To Reproduce**
In our case, we used a combination of SohoBarComponent and SohoChartComponent components on a single page.

**Expected behavior**
The setSelected() function on the bar chart should operate on the correct dataset.

**Version**
4.93.1

**Comment by tmcconechy** [comment]
@DavidMoerman seems like you have an idea for the fix. My line numbers might not match up. Maybe try to do a Pull Request with the fix and I can review it.

**Comment by DavidMoerman** [comment]
@tmcconechy Sorry I missed your reply. I have edited the final sohoxi.js file, I hope you can derive the necessary changes from that (if you run a diff, there are just my couple of changes). Both files (version 4.92.2) are attached here.
[sohoxi_patched.zip](https://github.com/infor-design/enterprise-ng/files/15158661/sohoxi_patched.zip)

**Comment by tmcconechy** [comment]
@DavidMoerman Does it have anything to do with unique ID's? Only an initial guess you could check. We'll take a look if we can.

**Comment by DavidMoerman** [comment]
I don't know how this is working exactly in the Soho Controls, but the "bad" version of the function does not use the "internals" variable, which contains the svg image for the specific graph object.

**Comment by tmcconechy** [comment]
@DavidMoerman im not sure how to match that back. Maybe you can update the code repo on a branch and push the branch with the proposed fix?

i.e. - branch , change the code and push branch

**Comment by DavidMoerman** [comment]
Hi Tim, you asked that earlier, but it would take me too much time to investigate where to make changes in the soho sources. I only patched the final sohoxi.js file. Did you check the zip file I provided two weeks ago?

**Comment by tmcconechy** [comment]
@DavidMoerman yes i see the diff. But not sure if it would be correct since you removed the internals variable and its getting passed in several places. In your estimation does it fix the issue?

It looks like the fix would go here https://github.com/infor-design/enterprise/blob/main/src/components/charts/charts.js 

I made a new example with 2 bars and 2 lines and i think i see the issue https://main-enterprise.demo.design.infor.com/components/charts/multiple-charts.html

1. When i remove the lines i can select the bar charts
2. When i add the line charts they dont work independently to select and then the bar stops

This must be the issue right?

**Comment by DavidMoerman** [comment]
@tmcconechy The example provided indeed shows the issue. However, the patch I provided does not **remove** the internals variable, but **adds** it (the file with _patched in the name is the one that fixes the problem, for us at least).

**Comment by tmcconechy** [comment]
@DavidMoerman then i guess the problem is that the patch is for an older version the code has since changed so it doesnt match for me.

Check out https://github.com/infor-design/enterprise/blob/main/src/components/charts/charts.js#L1045 where the change should go. Maybe you can patch that file instead? Then i can push it for you.


To test it:
1. clone this repo https://github.com/infor-design/enterprise
2. edit the file above `src/components/charts/charts.js` and add the changes
3. run `npm run build` and copy sohoxi.js from dist to your app and see
4. test http://localhost:4000/components/components/charts/multiple-charts.html

If you cant we can fix this in time but may use a different fix.

**Comment by DavidMoerman** [comment]
Hi Tim,

I think I prefer you fixing the issue - if that solves the problem in your own reproduction example of 3 weeks ago mentioned above, I am pretty sure it'll solve ours as well.

**Comment by tmcconechy** [comment]
@DavidMoerman ok will try and file it into a sprint
