### ISSUE TITLE
Timepicker: Add Support for HHmmss Format

### ISSUE THREAD

**Issue by eaenriquez** [infor-design/enterprise-ng#1691]
We would need the timepicker to allow a typing `HHmmss` 

We need this; because in M3, we support a 24-hour military time format without the separators (HHmmss) so it would be helpful to just type in the numbers, so both typing or using the timepicker will be up to the user

To be more specific, we aim to support the cases such as:

1. manually type in the time, bypass the timeformat, thus without live-formatting
2. use the timepicker popup to set the time, this will obey whatever timeformat is used

**Comment by tmcconechy** [comment]
@eaenriquez not 100% sure i get the ask. Is it more simply

1) Support `HHmmss` format with no separator?
2) and/or turn off masking (so they can even type letters and part times that are incorrect in it)

**Comment by eaenriquez** [comment]
Hi @tmcconechy 
1. Yes either `HHmmss` or no formatting at all would be okay, without separators. As long as the user can type in freely.
2. Yes, that might fix the entire problem, such as a property to turn off masking.

Turning off masking would probably turn off validation too, right?

**Comment by tmcconechy** [comment]
Turn off masking can be done and leave validation on.  But since no separators are not currently supported i think the validation will be wrong and the timepicker will not show the right value in the popup for whats in the field.

I think we simply need to support `HHmmss`. If we do it wont guide you to adding `:` ect and work (if we can do it because the algorithm relies on seperators)

**Comment by eaenriquez** [comment]
I agree on that solution, I think that will work for us :+1:

**Comment by eaenriquez** [comment]
Supporting `HHmmss` that is ..
