### ISSUE TITLE
Datagrid grouping pagination not working

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise-ng#173]
**Describe the bug**
We have observe
[Datagrid grouping.docx](https://github.com/infor-design/enterprise-ng/files/2326578/Datagrid.grouping.docx)
d that datagird grouping pagination is not working  
**To Reproduce**
1. Go to 'Create datagrid with grouping, assign some data to get pagination'
2. Click on 'When datagrid load in browser first page look okay, but when we click on next putton it show empty grid.'

**Expected behavior**
When we click on pagination it will show available records.

**Screenshots**
Please refer attached doc file for more details. 
**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
FYI - I did look at supporting this but its extremely difficult because the groups need to be calculated on the entire data set in order to group them correctly. The only way it might work is if

a) you can always provide the data sorted for server side data and can calculate it all on your server correctly.
b) we only support client side paging where we have all the data to work with

For now i suggest not using paging with grouping together. How big is the data set and what paging mode do you use?

**Comment by dhumalkishor** [comment]
We are using client side pagination. Data set is depend upon end users how much they create we need to show it. RemoveSelected() functionality not working.

**Comment by tmcconechy** [comment]
Descoping this issue for now
