### ISSUE TITLE
Auto suggest bug

### ISSUE THREAD

**Issue by JestoniFajardo** [infor-design/enterprise-ng#177]
**Describe the bug**
No Results options text was retained when textbox was cleared
No Results options text was displace upon Page Scroll

**To Reproduce**
1. Input text in the Search textbox which will result to 'No Results' text
2. Clear the inputted text in the Search textbox. Note the actual result.
3. Scroll the page. Note the actual result: "No Results text was retained upon Page Scroll"

**Expected behavior**
No Results text should not be displaced or retained when the *page was scrolled*. 
No Results text option will disappear after clearing text box.

**Screenshots**
See attached .gif for actual result
![autosuggestbug](https://user-images.githubusercontent.com/42030487/44992159-0ad7c400-afc9-11e8-86de-d38f16223d38.gif)

**Note**
*X* button is not displaying on the textbox due some configuration settings issue which not rendered the svg path.

**Comment by tmcconechy** [comment]
I think that the list should close on scroll already. But it will only do so if the parent scroll area uses our internal class "scrollable" as the code is looking for this (or if the scroll area is body).

So see if you can change the area that scrolls under the header to have class "scrollable" instead of using your own internal css to do that. This will maybe solve your issue.

**Comment by tmcconechy** [comment]
Did adding the scrollable class solve the issue for you?

**Comment by tmcconechy** [comment]
This should be solved by adding / changing around the scrollable areas so it can find the scrollable class
