### ISSUE TITLE
 SoHo data grid (Table) Cell Alignment  

### ISSUE THREAD

**Issue by rishni** [infor-design/enterprise-ng#237]
![1](https://user-images.githubusercontent.com/44457011/47491372-58094100-d868-11e8-9e27-99cfd9584198.jpg)

SoHo data grid (Table) Cell Alignment occurred when data with the filter feature. We can't put data in <p> tag because then filter feature not work proper way. Then, this cell alignment issue shows like the above image.

**Comment by tmcconechy** [comment]
I think this is not strictly an angular issue, so please raise this over at https://github.com/infor-design/enterprise/issues

Remember to
- Follow the bug template
- Add the columns array, sample data and grid settings you use, so that we can reproduce this on our end. 
- this may be similar to whats seen on http://master-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html
