### ISSUE TITLE
Donut: Legend placement is not working in angular, it always displays on the right

### ISSUE THREAD

**Issue by jayblack-infor** [infor-design/enterprise-ng#329]
**Describe the bug**
Using the attribute legendPlacement to place the legend at the bottom is not working.   The legend always displays on the right

**To Reproduce**

1. In your html do the following:
```
<div soho-pie [dataset]="donutData" [isDonut]="true" [showLegend]="true" **[legendPlacement]="bottom"** [showLinesMobile]="true" [lines]="lines" ></div>
```

**Expected behavior**
When using the legendPlacement attribute and setting the value to bottom the legend appears at the bottom and not on the right.

**Version**
- ids-enterprise-ng: [e.g. v4.7.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/45010485/51329399-0a513e80-1a3b-11e9-8bdf-974b7b3d6dee.png)

**Comment by tmcconechy** [comment]
Noting it does work on http://latest-enterprise.demo.design.infor.com/components/donut/example-legend-bottom.html for some reason the setting doesnt work in NG.

**Comment by pwpatton** [comment]
When using an input bindings like this angular really wants the right side to be a variable and not a constant (`[someInput]="true"` seems to be the exception). Angular does provide a mechanism to deal with this however.  Instead of using a binding (which really isn't needed for static input) use the variable w/o the brackets and surround the static value with double and single quotes. This allows for a static content to be passed into the component and seems to resolve this issue.

`legendPlacement="'bottom'"`
