### ISSUE TITLE
DataGrid - Exclude mandatory columns from personalization

### ISSUE THREAD

**Issue by MartinSchererInfor** [infor-design/enterprise-ng#346]
**Problem Data-Grid - Personalize columns**
It is not possible to exclude mandatory columns from personalization.
Means. mandatory columns can be marked as hidden.

**Describe the solution you'd like**
Mandatory columns should not appear in the personalization-dialog or 
mandatory columns should be shown in the personalization-dialog as disabled.

**Comment by tmcconechy** [comment]
There is an option in the main component set `hideable` where you can configure some columns to not be hideable by setting `hideable: false` on the column. It appears this option is not in the types for NG. All one would have to do to solve this issue is add it : https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.d.ts#L555 and test this out.

**Comment by mirekrewak** [comment]
I've create PR with hideable option to column definition. Marked columns will be disabled in the personalization dialog.

**Comment by tmcconechy** [comment]
Marking this as resolved since the PR solves this
