### ISSUE TITLE
(selected) event does not work on soho-popupmenu when hosted in a toolbar.

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise-ng#492]
**Describe the bug**

Adding a `selected` event handler to a `soho-popupmenu` does not get called when the associated item is selected.

**To Reproduce**

Clone the ids-enterprise-ng repo.
Edit `toolbar-flex-basic.demo.html`:

```html
<soho-toolbar-flex-more-button>
  <ul soho-popupmenu (selected)="onSelected($event)">
  <li soho-popupmenu-item><a soho-popupmenu-label>Pre-defined Item #1</a></li>
  <li soho-popupmenu-item><a soho-popupmenu-label>Pre-defined Item #2</a></li>
  <li soho-popupmenu-item><a soho-popupmenu-label>Pre-defined Item #3</a></li>
 </ul>
</soho-toolbar-flex-more-button>
```

```sh
npm i
npm run build:lib
npm run start
```

**Expected behavior**

I would expect the `onSelected` method to be called.  

The events are available from the `soho-toolbar (selected)` output, however this makes it harder to write reusable toolbar components that can be added to multiple toolbars without affecting the container's code. 

If the events are deliberately bubbled up to the toolbar, then perhaps a boolean config property could be added (`emitOnSource`) to allow the events to be obtained from the source control.

**Version**
- ids-enterprise-ng: 5.3

**Screenshots**

**Platform**

**Additional context**

**Comment by tmcconechy** [comment]
Did you talk to @EdwardCoyle about this one @bthharper ?

**Comment by EdwardCoyle** [comment]
Want to loop @Sovia on this as well, since she's familiar with the Flex Toolbar component.

----

I'm not sure 100% about the NG side of the interaction, but in EP, [we intercept the `selected` event](https://github.com/infor-design/enterprise/blob/master/src/components/toolbar-flex/toolbar-flex.item.js#L414) on Popupmenu in the "more" button.  The Flex Toolbar has a process for firing a `selected` event on the original button (or popupmenu item) associated with a More Actions menu item, instead of allowing the selected event in the More Button to occur.  The intention for this is because its attached menu is technically just made up of shadow elements for the real toolbar items.  The `onSelected` handler that would be attached at the Toolbar level catches the `selected` event regardless of whether it comes from the more menu, or the real toolbar item. The original toolbar has a similar process.

That being said, I'm not really sure what would be an appropriate change here, because that particular interaction is pretty key to how the whole toolbar works.

**Comment by bthharper** [comment]
@EdwardCoyle  - understood.    I am trying to implement reusable components that can be dropped into any toolbar (more menu) without having to make changes to the toolbar or the component that sits in.  At the moment I have to add additional code to all the toolbars to then call back to the reusable component.

**Comment by ahnpnl** [comment]
I encountered the same problem as well.

**Comment by tmcconechy** [comment]
Descoping this for now but should work in 5.x
