### ISSUE TITLE
Add auto-complete feature to soho-lookup component

### ISSUE THREAD

**Issue by rvilleno** [infor-design/enterprise-ng#647]
**Is your feature request related to a problem? Please describe.**
Trying to create a feature where in you can do both look-up and/or auto-complete when typing on a field.

**Describe the solution you'd like**
Using the soho-lookup component, I would like to have an auto-complete feature with it.

**Describe alternatives you've considered**
I have used the soho-autocomplete and added a button on the right. it kinda feels a bit off since we do have a soho-lookup field component.

**Additional context**

![05788c4e-0a26-48a4-b08d-91833adfb1ce](https://user-images.githubusercontent.com/10869544/67179037-8f70e600-f407-11e9-866c-fd84861fee3d.jpg)

**Comment by tmcconechy** [comment]
We do have an example in regular EP components that shows a lookup along with autocomplete.
Example: http://localhost:4000/components/lookup/test-autocomplete-and-lookup.html
When you type it shows the autocomplete and when you open it it shows the lookup.

Source: https://github.com/infor-design/enterprise/blob/master/app/views/components/lookup/test-autocomplete-and-lookup.html

This may be trickier in Angular as you can only have one component on an input. But you could as a workaround manually invoke the plugin in a non angular way on a lookup input.

We could consider doing this in some better angular way perhaps by making a new component or setting on the lookup to invoke the autocomplete.

This issue is available for a pull request if you want to attempt it.

**Comment by pwpatton** [comment]
@tmcconechy  @bthharper could the auto-complete be done with a Directive? Then it could be applied to any input field.

**Comment by tmcconechy** [comment]
Thats another option. I would assume it could be.

**Comment by pwpatton** [comment]
I love that idea. @rvilleno @nbcp could you take a quick look into that and see what might need to be done?

**Comment by tmcconechy** [comment]
Descoping this for now

**Comment by Sovia** [comment]
Reopening this issue. I would be nice if the SohoAutoComplete settings on soho-lookup could have a call back, so we could be passed the typed in search term and do our own data retrieval (like dropdown does). I think this could make is so auto complete doesn't need to be refactored into a directive.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
