### ISSUE TITLE
Unable to create Pagination for Angular Listview for Homepage Widgets

### ISSUE THREAD

**Issue by Venketkm** [infor-design/enterprise-ng#687]
Hi,
I am able to see Pagination UI but it is not working properly. Please find issue details below : 

If number of records are 15 & page size = 6, then 3 pages are coming in UI. 
But all records are coming in 1st page itself. 

Expected behaviour is First page should consist of only 6 records, when we click on page 2 ,next 6 records should come.

In Angular examples of cardlist there is no example of Pagination.

**Comment by tmcconechy** [comment]
@Venketkm 
1. When entering issues please use the issue or enhacement template https://github.com/infor-design/enterprise-ng/issues/new/choose - if you can edit this issue that would be great.
2. Did you succeed in an example? If so can you update it so we can try your steps?
3. Or is this simply a issue of "please make an example of a listview with paging on a card list, we cant figure it out"? If so thats clear but the issue is a bit confusing to work on as is.

**Comment by Venketkm** [comment]
As mentioned created another issue [https://github.com/infor-design/enterprise-ng/issues/689] using mentioned template.
