### ISSUE TITLE
Listview: Unable to use Ng templates with Pagination

### ISSUE THREAD

**Issue by Venketkm** [infor-design/enterprise-ng#689]
**Describe the bug**
Unable to implement pagination for List View.

**To Reproduce**
HTML Snippet
<div class="card-content" *ngIf="showList">

	<soho-listview [paging]="true" [pagesize]="3" [dataset]="sortedItems" [searchable]="true">
	<input soho-searchfield
             [(ngModel)]="searchText" placeholder="Search" (change)="onSearchChange()" >
			<li soho-listview-item *ngFor="let item of sortedItems">
				<p soho-listview-header>
					<span>Contract: {{item.Contract}}</span>
					<span style="float:right">ContractGroup: {{item.ContractGroup}}</span>
				</p>
				<p soho-listview-subheader>
					<span>PrimaryContact: {{item.PrimaryContact}}</span>
					<span style="float:right">WorkingContractID: {{item.WorkingContractID}} 
                                        </span>
				</p>
				<p soho-listview-subheader>
					<span>ExpirationDate: {{item.ExpirationDate}}</span>
					<span style="float:right">Supplier: {{item.Supplier}}</span>
				</p>
			</li>
		</soho-listview>
	</div>
	<div class="card-footer" *ngIf="showList"></div>

**Expected behavior**
When PageSize is set to 6.  If Number of records are 15 then 3 pages should come. Each page must have 6 records and last page must have 3 records.

**Version**
- IDS Enterprise Components - v4.21.3

**Screenshots**
![image](https://user-images.githubusercontent.com/46643143/70968138-69418c80-20be-11ea-9151-54a506105db9.png)
.

**Platform**
 - Windows
 - OS Version: Windows 10
 - Browser Name chrome
 - Browser Version 79.0.3945.79

**Comment by tmcconechy** [comment]
We have an example of paging with a list view (EP) http://master-enterprise.demo.design.infor.com/components/listview/example-paging.html

I updated this example so that there are 15 records and the paging seems to work correctly. I notice your on 4.21.3 which is a bit old and we have had some fixes. My tests are on 4.24 (unreleased). So i assume the latest version will work for you and that we fixed this?

Also this example shows the structure of the card in HTML you might used (non angular but may help). https://github.com/infor-design/enterprise/blob/master/app/views/components/listview/example-paging.html#L7-L17

**Comment by volante007** [comment]
Hi,

I'd like to provide some additional context.

I've tested the same code / markup for a paged `soho-listview` using two different versions of ids/ids-ng, and the result differs quite a bit. The markup is as follows:

```
<div class="card-content">
   <soho-listview [paging]="true" [pagesize]="2" [dataset]="items" >
      <li soho-listview-item
	   *ngFor="let item of items">
         <p soho-listview-header>{{item.title}}</p>
	 <p soho-listview-subheader>{{item.description}}</p>
      </li>
   </soho-listview>
</div>
<div class="card-footer"></div>
```

I know I got this working half a year ago or so while helping another team, so that's why I tried in the following ids versions.

ids 4.14.0 / ids-ng 5.0.0:
![4_14_0](https://user-images.githubusercontent.com/1101770/71075381-3eba0700-2184-11ea-89b8-9daf64a2045d.gif)
The paging works perfectly fine. However, the pager only shows the current page, not all available ones. 

ids 4.21.3 / ids-ng 6.0.0:
![4_21_3](https://user-images.githubusercontent.com/1101770/71075549-8c367400-2184-11ea-9a39-c7296d43296f.gif)
The paging does not work (proper pages are shown though) 

There's been no change to the angular wrapper for the listview, as far as I can see, between these versions of ids-ng. So I'm thinking that something probably have changed in the core control between these versions that cause an Angular paging implementation to fail?

The paging does not work in latest versions either (4.23.0 / 6.2.0)

**Comment by volante007** [comment]
Ok, an update to above. It seems you need to provide a `template` as well.. I tried using the default template that is used in the sample you provided Tim.

`<soho-listview [paging]="true" [pagesize]="2" [dataset]="items" [template]="template"></soho-listview>`

```
template = `
	<ul>
	  {{#dataset}}
		 {{#disabled}}
			<li class="is-disabled">
		 {{/disabled}}
		 {{^disabled}}
			<li>
		 {{/disabled}}
			<p class="listview-heading">{{title}}</p>
			<p class="listview-subheading">{{description}}</p>
		 </li>
	  {{/dataset}}
	</ul>`;
```
Got paging working now. However, I think there might be issues with this approach? It's quite common to use `(click)` events on the items (or other Angular events), but how to incorporate that into the static template? For click event, you could get around it by using the `(selected)` `@Output` instead at least (the clicked item can be retrieved from its event data) :)

**Comment by tmcconechy** [comment]
Ok @volante007 - good findings and that makes a lot of sense as expected.
We werent aware it was even possible to render an NG template with a ngFor and have it work with paging. We made some refactoring to the paging and now it will for performance rerender the "built in" template on the pages.

So i think for now you have to use the built in template as you noted. Otherwise its just rendering what you put in the body and the paging logic doesnt know what to do.

You could handle the clicking with the component level click/select events. That would be logical.
I think at some point we could reworks this, so making this an enhancement.

**Comment by pwpatton** [comment]
In Landmark we are managing the paging bar ourselves with the `soho-standalone-pager.component.ts` but I realize pager.js doesn't support the full pager bar functionality (only the indeterminate paging).

**Comment by Venketkm** [comment]
I am able to get Pagination for listview using @volante007 suggestion.

**Comment by tmcconechy** [comment]
Ok, Im going to close this for now. If we have time in the future we could potentially change it (somehow) to work with NG templates
