### ISSUE TITLE
SVG in Popup menu for RTL

### ISSUE THREAD

**Issue by DivyaParepally** [infor-design/enterprise-ng#734]
While placing svg in popupmenu as mentioned below, in RTL it is not rendering in reverse order.

    <ul class="popupmenu has-icons is-selectable">
      <li><a href="#">
        <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
          <use xlink:href="#icon-folder"></use>
        </svg>
        <span>Create new folder</span>
      </a></li>
    </ul>

In LTR: 
![image](https://user-images.githubusercontent.com/48956283/74520150-0002bc00-4f3d-11ea-9715-1562f3a424ef.png)

In RTL: 
![image](https://user-images.githubusercontent.com/48956283/74520218-1f99e480-4f3d-11ea-81cb-f97562dfbe7c.png)

Expected Result in RTL: 
![image](https://user-images.githubusercontent.com/48956283/74520417-85866c00-4f3d-11ea-9095-b125b08d0dac.png)

**Comment by tmcconechy** [comment]
We do not support the icon on the right side. The icon should go on the left side (LTR). See https://master-enterprise.demo.design.infor.com/components/contextmenu/example-index.html and https://master-enterprise.demo.design.infor.com/components/contextmenu/example-index.html?locale=ar-SA

If doing that everything will correctly flip. This is important as we will add additional info (keyboard shortcuts) to the right side so that will conflict further if you continue to use the wrong markup.

Should be like this instead https://github.com/infor-design/enterprise/blob/master/app/views/components/contextmenu/example-index.html#L24-L31

**Comment by tmcconechy** [comment]
Closing...as we wont support this
