### ISSUE TITLE
PopupMenu: popupmenu-item that removes itself causes page navigation

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#807]
**Describe the bug**
A `soho-popupmenu-item` that is conditionally shown (using `*ngIf`) will cause a page navigation when clicked, if that click handler causes the menu item to be removed.

**To Reproduce**
1. Go to https://anhallbe.github.io/ids-repro/popupmenu-navigation
2. Click on the context menu
3. Click on the popupmenu-item
4. Page will *sometimes* navigate to `/#` and then to `/`.

**Expected behavior**
Popupmenu-items should not affect the routing state.

**Version**
- ids-enterprise-ng: 7.0.2

**Platform**
 - Browser Name: chrome, firefox, safari

**Additional context**
Original issue (where this bug causes router navigation, which destroys dialogs due to `@angular/router`): https://jira.infor.com/browse/LIME-6019

Source code for repro: https://github.com/anhallbe/ids-repro/tree/master/src/app/popupmenu-navigation

**Comment by tmcconechy** [comment]
We had this issue in the past. What we normally had done is preventDefault on the click and use the component selected event. So i think you have three choices.

1) Instead of click use the popupmenu selected event
2) in the item add href="#'.
```
 <a soho-popupmenu-label (click)="hideItem()" href="#">...but this will not</a>
```
3) add e.preventDefault in the click handler.
```
(click)="hideItem($event)"
```

```
  hideItem(event: Event) {
    this.showItem = false;
    setTimeout(() => {
      this.showItem = true;
    }, 1000);
   event.preventDefault()
  }
```

I think internally it does it but somehow the way your handling this its not getting here https://github.com/infor-design/enterprise/blob/master/src/components/popupmenu/popupmenu.js#L1342 to stop navigation?

**Comment by tmcconechy** [comment]
I believe this issue was recently fixed in EP
