### ISSUE TITLE
Lookup: Required validation does not respond to selection

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise-ng#810]
**Describe the bug**
A `soho-lookup` field can become stuck in a "required" state even when an item is selected.

**To Reproduce**
1. Go to https://anhallbe.github.io/ids-repro/lookup
2. Open the lookup modal & select a value
3. Remove the contents of the field
4. Open the lookup again & select a value
5. The field now has a value, but a "required" warning is still present.

**Expected behavior**
The "required" warning should only be visible if the field is empty.

**Version**
- ids-enterprise-ng: 7.0.2

**Screenshots**
![lookup-required](https://user-images.githubusercontent.com/4991954/81048527-cb0f6100-8ebc-11ea-8fb9-7267195bc228.gif)

**Platform**
- Windows, MacOS
- Chrome, Firefox

**Additional context**
Possibly a minor issue.. Context:
https://jira.infor.com/browse/LIME-5663

**Comment by tmcconechy** [comment]
I found this can be reproduced in EP. Steps:

- http://localhost:4000/components/lookup/example-index.html
- in the first field click icon and select a value
- in the field clear the value text
- open the lookup again and select the same value as b again (value doesnt go away)

**Comment by jbrcna** [comment]
**QA Failed**
The issue was Failed in Firefox. A keypress or lose focus is needed to remove the validation.
I also tried the same scenarios in EDGE (using BrowserStack) but it works fine
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/lookup/example-index.html
![image](https://user-images.githubusercontent.com/56722184/84139681-e30d6e00-aa82-11ea-9f7e-459a166bd467.png)

**Comment by tmcconechy** [comment]
@jbrcna Can you clarify the steps for the failed QA? I cannot reproduce anything wrong

- Mac / FF
- Tab out of the first field (error appears)
- Click and select a value (error goes away)
