### ISSUE TITLE
Datagrid: isList attribute in template doesn't work for a certain set of configurations

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise-ng#814]
**Describe the bug**
isList="true" in template doesn't work for a certain combination of configurations.

Specifically:
isList="true" in template html
hidePagerOnOnePage: true in gridOptions in .ts

**.ts**
```
this.gridOptions = {
   hidePagerOnOnePage: true,
};
```
**.html**
```
<div soho-datagrid *ngIf="gridOptions" 
  isList="true"
  [gridOptions]="gridOptions"
  [columns]="EDITORS_COLUMNS"
  [data]="EDITORS_DATA"
  [paging]="true"
  [toolbar]="{results: true, keywordFilter: true}"
  [pagesize]="10"
></div>
```

**To Reproduce**
I updated `datagrid-angular-editor.demo.html` and `datagrid-angular-editor.demo.ts ` to reproduce this scenario. Please paste the files in zip file into enterprise-ng/src/app/datagrid and run the ng demo app and go to to .../datagrid-angular-editor.

[datagrid-angular-editor.demo.zip](https://github.com/infor-design/enterprise-ng/files/4615942/datagrid-angular-editor.demo.zip)

You will notice that isList="true" doesn't work and datagrid is not shown as list.

<img width="1659" alt="Screenshot 2020-05-12 at 3 35 43 PM" src="https://user-images.githubusercontent.com/1594815/81699068-25816200-9467-11ea-9148-7fcfa946d4e7.png">

**Expected behavior**
 isList="true" should work in template html for any combination of configurations.

**Version**
- ids-enterprise-ng 7.0.3 (This issue doesn't exist on earlier versions. Seems to have been introduced in v7.0.3)

**Additional context**
Infor PIM @karinthulin

**Comment by tmcconechy** [comment]
I think this is the same as https://github.com/infor-design/enterprise-ng/issues/805 really. But will keep it seperate until thats complete. I suggest that you do the settings in `gridOptions` and have only that in the template rather than mixing these. Its better to have them in the TS file in my opinion rather than putting them in both places

**Comment by hemantg05** [comment]
@tmcconechy , yes, it is better to put them in one place. But we had to put hidePagerOnOnePage in gridOptions because of https://github.com/infor-design/enterprise-ng/issues/771.

So going back to our original implementation and removing the work around for hidePagerOnOnePage will be workaround for this bug.

As configs are also supported on template, I preferred to have all configs in the template. If configs in templates are not recommended, then in my opinion, it is better to deprecate them and eventually remove them in future releases.

**Comment by tmcconechy** [comment]
Well both are supported (if it has an input created). This has caused issues as the inputs get forgotten but if they are anyone can just do a pull request and fix it 👍 

My personal preference is in the JS for something with a lot of options like a datagrid. And then the template for small sets.

The issue here is possibly merging some in the template with the JS.

**Comment by tmcconechy** [comment]
Descoping for now
