### ISSUE TITLE
Popupmenu: Setting isSelectable to false on popupmenu items does not work.

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise-ng#864]
**Describe the bug**
If you set isSelectable="false" on a popup menu item. It becomes selectable.

**To Reproduce**
1. In src\app\popupmenu\popupmenu.demo.html, add isSelectable="false"  on a pop up menu item.
2. View it in the browser, it is selectable and will have a checkmark next to it if you select it.

**Expected behavior**
Setting this value to false should make it not have the checkmark.

**Version**
- ids-enterprise-ng: 7.2.0

**Screenshots**

![image](https://user-images.githubusercontent.com/4143306/87100617-bbd0ca80-c201-11ea-8ed7-dfee513f3173.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 83.0.4103.116 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I think perhaps its a bug as it might be better if ` isSelectable="false"` worked. Its sort of two things.

1) the `singleSelectableSection` is also in play
2) seems to be checking for presense of isSelectable instead of false/true

So you can get around this by removing the property entirely and taking it out of the selection section...
```
    <li soho-popupmenu-item><a soho-popupmenu-label>Data validation</a></li>
      <li soho-popupmenu-separator singleSelectableSection="true"></li>
      <li soho-popupmenu-item isChecked="true" isSelectable="true"><a soho-popupmenu-label>Conditional formatting</a></li>
  ```

**Comment by tmcconechy** [comment]
Descoping this issue unable to fix right now
