### ISSUE TITLE
Dropdown Multiselect: Ajax source function with ManagedByTemplate set to true

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise-ng#885]
**Describe the bug**
When a ajax callback has managed by template set to true, the div isn't getting updated with the new options.

This probably requires a fix in ep, but is only seen thru the angular wrapper.

**To Reproduce**
1. Go to copy [dropdown-multiselect-landmark.demo.zip](https://github.com/infor-design/enterprise-ng/files/5023207/dropdown-multiselect-landmark.demo.zip) into your codebase src/app/dropdwon and hook it up into the angular guts
2. Navigate to the demo component
3. Open the Using Alpha Source and Tooltop field, and enter the value 'c' in the dropdown's search box
4. See error. This values in the dropdown don't get updated

**Expected behavior**
The dropdown values should be updated to reflect what is in the angular template now. If you open the dom explorer, and see what options are under the select, they do not match what is in the dropdown's popupmenu

**Version**
- ids-enterprise-ng: latest

**Screenshots**
On load:
![image](https://user-images.githubusercontent.com/22107636/89318221-7d85ca00-d64c-11ea-862b-20114c12691e.png)

First Open:
![image](https://user-images.githubusercontent.com/22107636/89318254-8a0a2280-d64c-11ea-80d0-3cc2546661ca.png)

Entering a 'c' search value:
![image](https://user-images.githubusercontent.com/22107636/89318290-955d4e00-d64c-11ea-8fe2-1a221b2e87e2.png)

DOM options:
![image](https://user-images.githubusercontent.com/22107636/89318358-aefe9580-d64c-11ea-824e-51f40d80b56d.png)

**Platform**
 - Any

**Additional context**
The demo component I've written for this case is as close as the true landmark usecase as possible.

**Comment by vonnyw** [comment]
@tmcconechy @EdwardCoyle Can you please include this fix in 4.31? Thanks.

**Comment by EdwardCoyle** [comment]
We started looking at this and determined that the issue lies in the [`SohoDropDownControlValueAccessorDelegator`](https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/dropdown/soho-dropdown.component.ts#L671), specifically in the part that deciphers Angular's [addition of an index number](https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/dropdown/soho-dropdown.component.ts#L740-L752) to every `<option>` element's value.  We suspect that it's not handling multiple values correctly when stored.

I looked at how the [standard Angular implementation](https://github.com/angular/angular/blob/master/packages/forms/src/directives/select_multiple_control_value_accessor.ts#L158-L179) does it... wondering if we need to only stringify a single value in that `buildValueString` method, instead of concatenating them all to a single line?

**Comment by tmcconechy** [comment]
Wonder if  @bthharper has any clues?
